import {splitMeshes} from './selection.js';
import * as T from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {sessionData,dxf,csv,ifc} from './exporters.js';
import {components,axisValue,projectedEnd,detectElevations} from './measurement.js';
import {dimensionLayout} from './dimensions.js';
const $=id=>document.getElementById(id), view=$('view'), status=$('status');
const scene=new T.Scene();scene.background=new T.Color('#101820');
const backgroundColors={dark:'#101820',white:'#ffffff',sky:'#a6e3f5'};
function setBackground(value){
 const selected=Object.hasOwn(backgroundColors,value)?value:'dark';
 scene.background.set(backgroundColors[selected]);$('background').value=selected;
 try{localStorage.setItem('odr-skp-background',selected);}catch(e){}
}
let savedBackground='dark';try{savedBackground=localStorage.getItem('odr-skp-background')||'dark';}catch(e){}
setBackground(savedBackground);$('background').onchange=()=>setBackground($('background').value);
let camera=new T.PerspectiveCamera(42,1,.01,10000);camera.up.set(0,0,1);
const renderer=new T.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));view.prepend(renderer.domElement);
let controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;
scene.add(new T.HemisphereLight(0xffffff,0x526575,2.5));const sun=new T.DirectionalLight(0xffffff,2);sun.position.set(30,-30,60);scene.add(sun);
const modelGroup=new T.Group(), marks=new T.Group();scene.add(modelGroup,marks);
const pointer=new T.Mesh(new T.SphereGeometry(.065,12,8),new T.MeshBasicMaterial({color:0x67ffd4,depthTest:false}));pointer.renderOrder=99;pointer.visible=false;scene.add(pointer);
const ray=new T.Raycaster();let model,mode='navigate',zero=0,levels=[],measurements=[],pending=null,down,hit=null,extent=50;
let viewEdits={meshes:{},edges:{},groups:[],layers:[]};
let edgesVisible=false;try{edgesVisible=localStorage.getItem('odr-skp-edges')==='true';}catch(e){}
let rotationLocked=false;try{rotationLocked=localStorage.getItem('odr-skp-rotation-lock')==='true';}catch(e){}
const selected=new Set();let currentView='iso',depthPick=null;
function pickElement(e){if($('selectionTarget').value==='edges')return pickEdge(e);const rect=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new T.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const indices=[...new Set(ray.intersectObjects(modelGroup.children.filter(o=>o.visible),false).map(h=>h.object.userData.index))];if(!indices.length){if(!e.shiftKey&&!e.ctrlKey)selected.clear();depthPick=null;updateSelection();return;}let index=indices[0];if(e.altKey&&depthPick&&Math.hypot(e.clientX-depthPick.x,e.clientY-depthPick.y)<6){const next=indices.indexOf(depthPick.index)+1;index=indices[next%indices.length];}depthPick={x:e.clientX,y:e.clientY,index};applySelection([index],e);updateSelection();msg('Seleccionado: '+model.meshes[index].name+' · '+indices.length+' piezas bajo el cursor.');}
function updateSelection(){if($('propertyInfo'))showSelectionProperties();
 modelGroup.children.forEach((mesh,i)=>mesh.material.emissive.set(selected.has(i)?'#966100':'#000000'));
 $('selectedItems').replaceChildren();const box=new T.Box3();
 for(const index of selected){const mesh=modelGroup.children[index];if(!mesh)continue;mesh.geometry.computeBoundingBox();box.union(mesh.geometry.boundingBox);const row=document.createElement('div');row.className='item';const button=document.createElement('button');button.textContent='×';button.title='Quitar de la selección';button.onclick=()=>{selected.delete(index);updateSelection();};const name=document.createElement('span');name.textContent='#'+(index+1)+' '+model.meshes[index].name;name.style.fontSize='12px';row.append(button,name);$('selectedItems').append(row);}
 if(!selected.size){$('selectionInfo').textContent='Ningún elemento seleccionado.';return;}
 const size=box.getSize(new T.Vector3());$('selectionInfo').textContent=`${selected.size} piezas seleccionadas · X ${fmt(size.x)} · Y ${fmt(size.y)} · Z ${fmt(size.z)} · Z mín ${fmt(box.min.z-zero)} / máx ${fmt(box.max.z-zero)}`;
}
function syncVisibility(){Array.from($('groups').querySelectorAll('input')).forEach((input,i)=>input.checked=modelGroup.children[i].visible);}
function restoreVisibility(){modelGroup.children.forEach(m=>m.visible=true);syncVisibility();msg('Todos los elementos visibles.');}
$('isolate').onclick=()=>{if(!selected.size)return msg('Selecciona una o más piezas para aislar.');modelGroup.children.forEach((m,i)=>m.visible=selected.has(i));syncVisibility();msg('Aisladas '+selected.size+' piezas. Usa Mostrar todo para recuperar el modelo.');};
$('hideSelected').onclick=()=>{if(!selected.size)return msg('Selecciona las piezas que quieres ocultar.');for(const i of selected)modelGroup.children[i].visible=false;syncVisibility();msg('Selección oculta. Usa Mostrar todo para recuperarla.');};
$('restoreVisible').onclick=restoreVisibility;$('clearSelected').onclick=()=>{clearEdgeSelection();selected.clear();depthPick=null;updateSelection();};
$('fitSelected').onclick=()=>{if(!selected.size)return msg('Selecciona primero una pieza.');const box=new T.Box3();for(const i of selected){const mesh=modelGroup.children[i];mesh.geometry.computeBoundingBox();box.union(mesh.geometry.boundingBox);}fit(currentView,[box.min.toArray(),box.max.toArray()]);};
const fmt=v=>(v*($('units').value==='cm'?100:1)).toFixed($('units').value==='cm'?2:3)+' '+$('units').value;
const msg=t=>status.textContent=t;
async function connectionState(){
 try{const r=await fetch('/health',{cache:'no-store',signal:AbortSignal.timeout(3000)});if(!r.ok)throw Error('Servidor anterior');const h=await r.json();if(h.service!=='odr-skp-viewer')throw Error('Servidor no compatible');$('connection').textContent='Lector SKP conectado · puedes abrir otros archivos';$('connection').style.background='#16574b';return true;}
 catch(e){$('connection').textContent='Lector SKP desconectado o desactualizado. Ejecuta ABRIR_VISOR.cmd y vuelve a pulsar Abrir otro SKP. El modelo en pantalla sigue disponible.';$('connection').style.background='#793b2c';return false;}
}
connectionState();setInterval(connectionState,15000);
let labelAnchors=[];
const signed=v=>(v>=0?'+':'')+fmt(v);
function download(text,name,type='text/plain'){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),5000);}
function clear(group){for(const o of [...group.children]){o.traverse(child=>{child.geometry?.dispose();if(Array.isArray(child.material))child.material.forEach(m=>m.dispose());else child.material?.dispose();});group.remove(o);}}
function fit(which='iso',bounds=model.bounds){currentView=which;const b=new T.Box3(new T.Vector3(...bounds[0]),new T.Vector3(...bounds[1]));const center=b.getCenter(new T.Vector3());extent=b.getSize(new T.Vector3()).length();const d=Math.max(extent,.1)*1.35;controls.target.copy(center);camera.up.set(0,0,1);const dir={iso:[1,-1,.8],top:[0,0,1],bottom:[0,0,-1],front:[0,-1,0],back:[0,1,0],side:[1,0,0],left:[-1,0,0]}[which];if(which==='top')camera.up.set(0,1,0);camera.position.copy(center).add(new T.Vector3(...dir).normalize().multiplyScalar(d));camera.near=Math.max(extent/10000,.001);camera.far=Math.max(extent*100,100);if(camera.isOrthographicCamera){orthoHeight=2*d*Math.tan(42*Math.PI/360);camera.zoom=1;}resizeProjection();camera.updateProjectionMatrix();controls.update();}
function setMode(m){mode=m;controls.enableRotate=!rotationLocked&&m!=='select'&&m!=='hand';controls.mouseButtons.LEFT=m==='select'?null:m==='hand'?T.MOUSE.PAN:T.MOUSE.ROTATE;renderer.domElement.style.cursor=m==='hand'?'grab':'default';pending=null;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));$('tip').textContent={navigate:'Explorar · giro / desplazamiento / zoom',hand:'Mano · arrastra con botón izquierdo para desplazar · rueda para acercar',select:'Clic: seleccionar · Ctrl: añadir · Shift: quitar · Alt: recorrer profundidad',measure:'Selecciona el primer punto',dimension:'Cota: selecciona el primer punto',level:'Selecciona un punto para registrar su nivel',zero:'Selecciona el punto que representa ±0,00'}[m];pointer.visible=false;}
function loadModel(data){if(data.schema!=='odr-skp-mesh-1'||data.units!=='m')throw Error('Formato de modelo no válido');clear(modelGroup);selected.clear();depthPick=null;model=data;levels=[];measurements=[];$('candidates').replaceChildren();zero=0;$('zero').value=0;pending=null;
 viewEdits={meshes:{},edges:{},groups:[],layers:[]};renderUserGroups();renderLayers();sourceMeshes=data.meshes;$('selectionTarget').value='pieces';$('selectionDetail').value='groups';rebuildGeometry();fit();renderLists();setMode('navigate');}
let sourceMeshes=[];
function rebuildGeometry(){clear(propertyIsolation);clearEdgeSelection();clear(modelGroup);selected.clear();depthPick=null;pending=null;model.meshes=splitMeshes(sourceMeshes,$('selectionDetail').value);const data=model;
 data.meshes.forEach((m,i)=>{const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(m.positions,3));g.computeVertexNormals();const mesh=new T.Mesh(g,new T.MeshStandardMaterial({color:new T.Color().setHSL(.54+(i%5)*.018,.13,.57+(i%4)*.04),side:T.DoubleSide,roughness:.85,polygonOffset:true,polygonOffsetFactor:1,polygonOffsetUnits:1}));mesh.userData.index=i;modelGroup.add(mesh);});
 $('modelName').textContent=data.source;$('groups').replaceChildren();data.meshes.forEach((m,i)=>{const label=document.createElement('label');label.className='group';const input=document.createElement('input');input.type='checkbox';input.checked=true;input.onchange=()=>modelGroup.children[i].visible=input.checked;const span=document.createElement('span');span.textContent=m.name;span.title=m.name;label.append(input,span);$('groups').append(label);});applyViewEdits();updateSelection();updateEdges();msg(`${data.meshes.length} piezas seleccionables · ${data.stats.triangles.toLocaleString()} triángulos. Cambiar separación restablece la visibilidad y selección.`);}
$('selectionDetail').onchange=()=>{$('selectionTarget').value='pieces';rebuildGeometry();setMode('select');};
function marker(p,color){const m=new T.Mesh(new T.SphereGeometry(extent/450,10,8),new T.MeshBasicMaterial({color,depthTest:false}));m.position.fromArray(p);marks.add(m);}
function addLabel(p,text,measurement=false){const el=document.createElement('div');el.className='levelLabel'+(measurement?' measureLabel':'');el.textContent=text;$('labelLayer').append(el);labelAnchors.push({el,p:new T.Vector3(...p)});}
function drawDimension(m){const layout=dimensionLayout(m);if(!layout)return;const points=layout.segments.flat().map(p=>new T.Vector3(...p));const g=new T.BufferGeometry().setFromPoints(points);marks.add(new T.LineSegments(g,new T.LineBasicMaterial({color:0xffe08c,depthTest:false})));if($('labels').checked)addLabel(layout.label,fmt(layout.value),true);}
function drawMarks(){clear(marks);$('labelLayer').replaceChildren();labelAnchors=[];
 levels.forEach(l=>{marker(l.p,0xffc475);if($('labels').checked){addLabel(l.p,l.name+'\nCota '+signed(l.p[2]-zero)+' · Z '+fmt(l.p[2]));const [a,b]=model.bounds;const g=new T.BufferGeometry().setFromPoints([[a[0],a[1],l.p[2]],[b[0],a[1],l.p[2]],[b[0],b[1],l.p[2]],[a[0],b[1],l.p[2]],[a[0],a[1],l.p[2]]].map(p=>new T.Vector3(...p)));marks.add(new T.Line(g,new T.LineBasicMaterial({color:0xffc475,transparent:true,opacity:.45})));}});
 measurements.forEach(m=>{if(m.dimension){drawDimension(m);return;}marker(m.a,0x6de0c3);marker(m.b,0x6de0c3);const b=projectedEnd(m.a,m.b,m.axis);const g=new T.BufferGeometry().setFromPoints([new T.Vector3(...m.a),new T.Vector3(...b)]);const color={x:0xff7777,y:0x83df88,z:0x7baeff}[m.axis]||0x6de0c3;marks.add(new T.Line(g,new T.LineBasicMaterial({color,depthTest:false})));if(m.axis&&m.axis!=='3d'){const extension=new T.BufferGeometry().setFromPoints([new T.Vector3(...b),new T.Vector3(...m.b)]);const line=new T.Line(extension,new T.LineDashedMaterial({color, dashSize:.15,gapSize:.1,depthTest:false}));line.computeLineDistances();marks.add(line);}if($('labels').checked)addLabel(m.a.map((v,i)=>(v+b[i])/2),`${m.name} · ${(m.axis||'3d').toUpperCase()}\n${fmt(axisValue(m.a,m.b,m.axis))}`,true);});if(pending)marker(pending,0xffffff);
}
function renderLists(){ $('levelCount').textContent=levels.length;for(const [id,items] of [['levels',levels],['measurements',measurements]]){$(id).replaceChildren();items.forEach((item,i)=>{const row=document.createElement('div');row.className='item';const input=document.createElement('input');input.value=item.name;input.onchange=()=>{item.name=input.value.trim()||('Registro '+(i+1));input.value=item.name;drawMarks();};const remove=document.createElement('button');remove.textContent='×';remove.title='Eliminar registro';remove.onclick=()=>{items.splice(i,1);renderLists();};const small=document.createElement('small');if(id==='levels'){small.textContent=`Cota ${signed(item.p[2]-zero)} · Z SKP ${fmt(item.p[2])}`;}else{const c=components(item.a,item.b);small.textContent=`${(item.axis||'3d').toUpperCase()}: ${fmt(axisValue(item.a,item.b,item.axis))}\nΔX ${signed(c.dx)} · ΔY ${signed(c.dy)} · ΔZ ${signed(c.dz)}\n3D ${fmt(c.distance)} · XY ${fmt(c.horizontal)}`;small.style.whiteSpace='pre-line';}row.append(input,remove,small);
 if(id==='levels'){const label=document.createElement('label');label.className='storey';const check=document.createElement('input');check.type='checkbox';check.checked=item.storey!==false;check.onchange=()=>item.storey=check.checked;label.append(check,document.createTextNode(' Planta IFC / nivel Revit'));const z=document.createElement('input');z.type='number';z.step='.001';z.className='cotaInput';z.value=(item.p[2]-zero).toFixed(3);z.title='Editar cota relativa (metros)';z.onchange=()=>{if(z.value.trim()&&Number.isFinite(Number(z.value))){item.p[2]=Number(z.value)+zero;renderLists();}};row.append(label,document.createTextNode('Cota (m) '),z);}
 if(id==='measurements'){const label=document.createElement('label');label.className='storey';const check=document.createElement('input');check.type='checkbox';check.checked=!!item.dimension;check.onchange=()=>{item.dimension=check.checked;if(!Number.isFinite(item.offset))item.offset=1;renderLists();};label.append(check,document.createTextNode(' Mostrar como cota'));row.append(label);if(item.dimension){const sep=document.createElement('input');sep.type='number';sep.step='10';sep.className='cotaInput';sep.value=(Number.isFinite(item.offset)?item.offset:1)*100;sep.title='Separacion de la cota (cm); negativa cambia el lado';sep.onchange=()=>{if(sep.value.trim()&&Number.isFinite(Number(sep.value))){item.offset=Number(sep.value)/100;drawMarks();}};row.append(document.createTextNode('Separación (cm) '),sep);}}
 $(id).append(row);});}drawMarks();}
function selectPoint(e){const rect=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new T.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const hits=ray.intersectObjects(modelGroup.children.filter(o=>o.visible),false);if(!hits.length)return null;const h=hits[0];let p=h.point.clone();if($('snap').value==='vertex'){let best=12,chosen=null;const raw=model.meshes[h.object.userData.index].positions;for(const idx of [h.face.a,h.face.b,h.face.c]){const v=new T.Vector3(...raw.slice(idx*3,idx*3+3));const proj=v.clone().project(camera);const distance=Math.hypot((proj.x+1)*rect.width/2-(e.clientX-rect.left),(1-proj.y)*rect.height/2-(e.clientY-rect.top));if(distance<best){best=distance;chosen=v;}}if(!chosen)return null;p=chosen;}return p.toArray();}
renderer.domElement.addEventListener('pointerdown',e=>{down=[e.clientX,e.clientY,e.button];if(mode==='select'&&e.button===0)renderer.domElement.setPointerCapture(e.pointerId);});
renderer.domElement.addEventListener('pointermove',e=>{if(mode==='hand'){pointer.visible=false;return;}if(mode==='select'){pointer.visible=false;if(down&&down[2]===0)showRectangle(e);return;}hit=selectPoint(e);pointer.visible=!!hit&&mode!=='navigate';if(hit){pointer.position.fromArray(hit);$('readout').textContent=`Z SKP ${fmt(hit[2])}\nCota ${signed(hit[2]-zero)}`;$('readout').style.whiteSpace='pre-line';let preview=pending?` · ${$('axis').value.toUpperCase()} ${fmt(axisValue(pending,hit,$('axis').value))}`:'';msg(`X ${fmt(hit[0])} · Y ${fmt(hit[1])} · Z ${fmt(hit[2])} · Cota ${signed(hit[2]-zero)}${preview}`);}else{$('readout').textContent='Z SKP —\nCota ±0,00 —';if(mode!=='navigate')msg('Acerca el cursor a un vértice o cambia a punto sobre superficie.');}});
renderer.domElement.addEventListener('pointerup',e=>{const start=down;down=null;selectionRect.style.display='none';if(!start||start[2]!==0||(mode==='navigate'||mode==='hand'))return;const dragged=Math.hypot(e.clientX-start[0],e.clientY-start[1])>4;if(mode==='select'){if(dragged)rectangleSelect(start,e);else pickElement(e);return;}if(dragged)return;const p=selectPoint(e);if(!p)return;if(mode==='zero'){zero=p[2];$('zero').value=zero;setMode('navigate');msg('Referencia ±0,00 definida.');}else if(mode==='level'){levels.push({name:'Nivel '+(levels.length+1),p});}else if(mode==='measure'||mode==='dimension'){if(!pending){pending=p;$('tip').textContent='Selecciona el segundo punto';}else{if(Math.hypot(...p.map((v,i)=>v-pending[i]))<1e-8){msg('El segundo punto debe ser distinto.');return;}if(mode==='dimension'&&axisValue(pending,p,$('axis').value)<1e-8){msg('La distancia en el eje elegido es cero. Selecciona otro punto.');return;}measurements.push({name:(mode==='dimension'?'Cota ':'Medida ')+(measurements.length+1),dimension:mode==='dimension',offset:Number($('dimensionOffset').value)/100,axis:$('axis').value,a:pending,b:p});pending=null;$('tip').textContent='Selecciona el primer punto';}}renderLists();});
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{setMode(b.dataset.mode);drawMarks();});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>fit(b.dataset.view));
$('units').onchange=()=>{renderLists();if($('selectionTarget').value==='edges')refreshEdgeSelection();else updateSelection();};$('labels').onchange=drawMarks;$('axis').onchange=()=>{pending=null;drawMarks();if(mode==='measure'||mode==='dimension')$('tip').textContent='Selecciona el primer punto · '+$('axis').value.toUpperCase();};$('zero').onchange=()=>{const z=Number($('zero').value);if(Number.isFinite(z)){zero=z;renderLists();$('candidates').replaceChildren();}};
$('addManual').onclick=()=>{if(!$('manualZ').value.trim())return msg('Escribe una cota en metros.');const z=Number($('manualZ').value);if(!Number.isFinite(z))return;levels.push({name:$('manualName').value.trim()||'Nivel '+(levels.length+1),p:[model.bounds[0][0],model.bounds[0][1],z+zero]});renderLists();};
const data=()=>({...sessionData(model,zero,levels,measurements),viewEdits});const meshes=()=>{if(!$('geometry').checked)return [];if($('exportSelected').checked&&!selected.size)throw Error('Selecciona piezas para exportarlas o desmarca Solo geometría seleccionada.');return model.meshes.filter((m,i)=>modelGroup.children[i].visible&&(!$('exportSelected').checked||selected.has(i))).map(m=>{const edit=viewEdits.meshes[meshKey(m)]||{},layer=layerFor(edit);return {...m,cadLayer:layer?.name||'SKP_MODELO',color:layer?.color||edit.color,transparency:edit.transparency??layer?.transparency??0,parameters:{...layer?.parameters,...edit.parameters}};});};
$('detectZ').onclick=()=>{try{const proposals=detectElevations(model.meshes.filter((m,i)=>modelGroup.children[i].visible),Number($('zTolerance').value)/100,Number($('zArea').value));$('candidates').replaceChildren();proposals.forEach(p=>{const row=document.createElement('div');row.className='item';const info=document.createElement('small');info.textContent=`Z ${fmt(p.z)} · Cota ${signed(p.z-zero)} · ${p.area.toFixed(1)} m²`;const add=document.createElement('button');add.textContent='Agregar';add.onclick=()=>{if(levels.some(l=>Math.abs(l.p[2]-p.z)<.001))return msg('Esta cota ya está registrada.');levels.push({name:'Nivel '+(levels.length+1),p:[...p.p],storey:true});renderLists();add.disabled=true;};row.append(add,info);$('candidates').append(row);});msg(`${proposals.length} cotas propuestas. Área acumulada de triángulos, puede incluir caras superpuestas. Revisa cuáles son plantas.`);}catch(e){msg(e.message);}};
for(const [id,ext,fn] of [['dxf','dxf',()=>dxf({...data(),cadEdges:cadExportEdges()},$('selectionTarget').value==='edges'&&$('exportSelected').checked?[]:meshes())],['ifc','ifc',()=>ifc(data(),meshes())],['csv','csv',()=>csv(data())],['revit','json',()=>JSON.stringify({...data(),levels:data().levels.filter(l=>l.storey)},null,2)]])$(id).onclick=()=>{try{if(!levels.length&&!measurements.length&&!(id==='dxf'&&cadExportEdges().length)&&!meshes().length)return msg('Registra niveles o medidas antes de exportar.');download(fn(),'levantamiento_skp.'+ext);msg('Exportación '+ext.toUpperCase()+' descargada.');}catch(e){msg('Error: '+e.message);}};
$('save').onclick=()=>download(JSON.stringify({...data(),bounds:model.bounds},null,2),'sesion_skp.json');$('restore').onclick=()=>$('session').click();
$('session').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;const d=JSON.parse(await file.text());if(d.schema!=='odr-skp-survey-1'||d.source!==model.source||d.units!=='m'||!Number.isFinite(d.zeroSourceZ))throw Error('La sesión no corresponde a este modelo');const valid=p=>Array.isArray(p)&&p.length===3&&p.every(Number.isFinite);if(!Array.isArray(d.levels)||!Array.isArray(d.measurements)||!d.levels.every(l=>typeof l.name==='string'&&valid(l.point))||!d.measurements.every(m=>typeof m.name==='string'&&valid(m.a)&&valid(m.b)))throw Error('Coordenadas no válidas');zero=d.zeroSourceZ;levels=d.levels.map(l=>({name:l.name,storey:l.storey!==false,p:[l.point[0],l.point[1],l.point[2]+zero]}));measurements=d.measurements.map(m=>({name:m.name,dimension:!!m.dimension,offset:Number.isFinite(m.offset)?m.offset:1,axis:['3d','x','y','z','xy'].includes(m.axis)?m.axis:'3d',a:[m.a[0],m.a[1],m.a[2]+zero],b:[m.b[0],m.b[1],m.b[2]+zero]}));$('zero').value=zero;restoreViewEdits(d.viewEdits);renderLists();msg('Sesión recuperada');}catch(e){msg(e.message);}};
for(const [id,show] of [['showAll',true],['hideAll',false]])$(id).onclick=()=>{modelGroup.children.forEach(m=>m.visible=show);$('groups').querySelectorAll('input').forEach(i=>i.checked=show);};
$('open').onclick=()=>{$('file').value='';$('file').click();};$('file').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(location.protocol==='file:'){msg('Abre ABRIR_VISOR.cmd para cargar otros SKP.');return;}$('open').disabled=true;$('open').textContent='Abriendo '+file.name+'…';msg('Convirtiendo '+file.name+'…');try{const r=await fetch('/convert?name='+encodeURIComponent(file.name),{method:'POST',body:file});const type=r.headers.get('Content-Type')||'';if(!r.ok){const error=type.includes('application/json')?(await r.json()).error:'El servidor no pudo convertir el archivo (HTTP '+r.status+'). Cierra la consola anterior y abre ABRIR_VISOR.cmd.';throw Error(error);}loadModel(await r.json());msg('Abierto '+file.name+' · '+model.stats.triangles.toLocaleString()+' triángulos.');}catch(e){msg(e instanceof TypeError?'No se pudo conectar al servidor. Ejecuta ABRIR_VISOR.cmd y vuelve a intentar.':e.message);}finally{$('open').disabled=false;$('open').textContent='Abrir otro SKP';$('file').value='';}};
let orthoHeight=100;
function resizeProjection(){const aspect=view.clientWidth/view.clientHeight;if(camera.isPerspectiveCamera)camera.aspect=aspect;else{camera.left=-orthoHeight*aspect/2;camera.right=orthoHeight*aspect/2;camera.top=orthoHeight/2;camera.bottom=-orthoHeight/2;}camera.updateProjectionMatrix();}
$('projection').onchange=()=>{
 const target=controls.target.clone(),old=camera,dist=old.position.distanceTo(target),orth=$('projection').value==='orthographic';
 if(orth){orthoHeight=2*dist*Math.tan(old.fov*Math.PI/360);camera=new T.OrthographicCamera(-1,1,1,-1,old.near,old.far);}
 else{camera=new T.PerspectiveCamera(42,1,old.near,old.far);const d=orthoHeight/old.zoom/(2*Math.tan(42*Math.PI/360));camera.position.copy(old.position).sub(target).normalize().multiplyScalar(d).add(target);}
 if(orth)camera.position.copy(old.position);camera.up.copy(old.up);camera.quaternion.copy(old.quaternion);controls.dispose();controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.copy(target);resizeProjection();setMode(mode);controls.update();msg(orth?'Proyección ortogonal: sin deformación por perspectiva.':'Proyección en perspectiva.');
};
function applySelection(indices,e){if(!e.ctrlKey&&!e.shiftKey)selected.clear();for(const i of indices){if(e.shiftKey)selected.delete(i);else selected.add(i);}updateSelection();}
const selectionRect=document.createElement('div');selectionRect.id='selectionRect';view.append(selectionRect);
function showRectangle(e){const r=renderer.domElement.getBoundingClientRect();Object.assign(selectionRect.style,{display:'block',left:Math.min(down[0],e.clientX)-r.left+'px',top:Math.min(down[1],e.clientY)-r.top+'px',width:Math.abs(e.clientX-down[0])+'px',height:Math.abs(e.clientY-down[1])+'px',borderColor:e.clientX<down[0]?'#23b879':'#398eff',borderStyle:e.clientX<down[0]?'dashed':'solid',background:e.clientX<down[0]?'#23b87922':'#398eff22'});}
// Clip in homogeneous coordinates so triangles crossing the near plane remain selectable.
function clipPolygon(poly,planes){for(const plane of planes){const next=[];for(let i=0;i<poly.length;i++){const a=poly[i],b=poly[(i+1)%poly.length],da=plane(a),db=plane(b);if(da>=0)next.push(a);if((da>=0)!==(db>=0)){const t=da/(da-db);next.push(a.map((v,j)=>v+(b[j]-v)*t));}}poly=next;if(!poly.length)break;}return poly;}
function rectangleSelect(start,e){if($('selectionTarget').value==='edges')return rectangleEdges(start,e);
 const r=renderer.domElement.getBoundingClientRect(),xmin=(Math.min(start[0],e.clientX)-r.left)/r.width*2-1,xmax=(Math.max(start[0],e.clientX)-r.left)/r.width*2-1,ymin=1-(Math.max(start[1],e.clientY)-r.top)/r.height*2,ymax=1-(Math.min(start[1],e.clientY)-r.top)/r.height*2,cross=e.clientX<start[0],picked=[];
 camera.updateMatrixWorld();const matrix=new T.Matrix4().multiplyMatrices(camera.projectionMatrix,camera.matrixWorldInverse),planes=[p=>p[3]+p[0],p=>p[3]-p[0],p=>p[3]+p[1],p=>p[3]-p[1],p=>p[3]+p[2],p=>p[3]-p[2],p=>p[0]-xmin*p[3],p=>xmax*p[3]-p[0],p=>p[1]-ymin*p[3],p=>ymax*p[3]-p[1]];
 modelGroup.children.forEach((mesh,i)=>{if(!mesh.visible)return;const p=model.meshes[i].positions,vertices=[];for(let j=0;j<p.length;j+=3)vertices.push(new T.Vector4(p[j],p[j+1],p[j+2],1).applyMatrix4(matrix).toArray());let matches;if(!cross)matches=vertices.length>0&&vertices.every(v=>planes.every(plane=>plane(v)>=-1e-9));else{matches=false;for(let j=0;j<vertices.length;j+=3)if(clipPolygon(vertices.slice(j,j+3),planes).length){matches=true;break;}}if(matches)picked.push(i);});
 applySelection(picked,e);msg((cross?'Ventana de cruce':'Ventana de contención')+' · '+picked.length+' piezas encontradas · '+selected.size+' seleccionadas.');
}
renderer.domElement.addEventListener('pointercancel',()=>{down=null;selectionRect.style.display='none';});
const cubeHost=document.createElement('div');cubeHost.id='navCube';cubeHost.title='Cubo de navegación: clic en caras, aristas o esquinas';view.append(cubeHost);
const cubeRenderer=new T.WebGLRenderer({alpha:true,antialias:true});cubeRenderer.setSize(128,128);cubeRenderer.setPixelRatio(Math.min(devicePixelRatio,2));cubeHost.append(cubeRenderer.domElement);
const cubeScene=new T.Scene(),cubeCamera=new T.PerspectiveCamera(35,1,.1,20);cubeCamera.up.set(0,0,1);
const cubeLabels=['DERECHA','IZQUIERDA','ATRÁS','FRENTE','PLANTA','INFERIOR'];
const cubeMaterials=cubeLabels.map(text=>{const c=document.createElement('canvas');c.width=256;c.height=256;const ctx=c.getContext('2d');ctx.fillStyle='#dce7ee';ctx.fillRect(0,0,256,256);ctx.strokeStyle='#344c5e';ctx.lineWidth=12;ctx.strokeRect(0,0,256,256);ctx.fillStyle='#18323d';ctx.font='bold 30px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,128,128);return new T.MeshBasicMaterial({map:new T.CanvasTexture(c)});});
const cubeMesh=new T.Mesh(new T.BoxGeometry(1,1,1),cubeMaterials);cubeScene.add(cubeMesh);
function updateCube(){const direction=camera.position.clone().sub(controls.target).normalize();cubeCamera.position.copy(direction.multiplyScalar(3.3));cubeCamera.up.copy(camera.up);cubeCamera.lookAt(0,0,0);cubeRenderer.render(cubeScene,cubeCamera);}
cubeRenderer.domElement.addEventListener('click',e=>{const r=cubeRenderer.domElement.getBoundingClientRect(),cr=new T.Raycaster();cr.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2),cubeCamera);const h=cr.intersectObject(cubeMesh)[0];if(!h)return;const dir=h.point.clone();for(const axis of ['x','y','z'])dir[axis]=Math.abs(dir[axis])>.32?Math.sign(dir[axis]):0;if(!dir.lengthSq())dir.copy(h.face.normal);const distance=camera.position.distanceTo(controls.target);camera.up.set(0,0,1);if(!dir.x&&!dir.y)camera.up.set(0,1,0);camera.position.copy(controls.target).add(dir.normalize().multiplyScalar(distance));controls.update();currentView=dir.z>.99?'top':'iso';msg('Vista orientada desde el cubo de navegación.');});

const toolbars=document.createElement('div');toolbars.id='toolbars';view.append(toolbars);
function toolbar(label,buttons){const bar=document.createElement('div');bar.className='toolbar';bar.setAttribute('role','toolbar');bar.setAttribute('aria-label',label);const title=document.createElement('span');title.className='toolbarLabel';title.textContent=label;bar.append(title);for(const config of buttons){const button=document.createElement('button');button.textContent=config.text;button.title=config.title||config.text;if(config.mode)button.dataset.mode=config.mode;if(config.view)button.dataset.view=config.view;if(config.id)button.id=config.id;button.onclick=config.action||(()=>{if(config.mode){setMode(config.mode);drawMarks();}else if(config.view)fit(config.view);else $(config.command).click();});bar.append(button);}toolbars.append(bar);}
toolbar('Vista',[{text:'3D',view:'iso'},{text:'Planta',view:'top'},{text:'Frente',view:'front'},{text:'Lateral',view:'side'},{text:'Perspectiva',id:'toolPerspective',action:()=>{$('projection').value='perspective';$('projection').onchange();}},{text:'Ortogonal',id:'toolOrtho',action:()=>{$('projection').value='orthographic';$('projection').onchange();}},{text:'Aristas',id:'toggleEdges',action:()=>{edgesVisible=!edgesVisible;try{localStorage.setItem('odr-skp-edges',edgesVisible);}catch(e){}updateEdges();}},{text:'Bloquear giro',id:'rotationLock',action:()=>{rotationLocked=!rotationLocked;try{localStorage.setItem('odr-skp-rotation-lock',rotationLocked);}catch(e){}controls.enableRotate=!rotationLocked&&mode!=='select'&&mode!=='hand';syncToolbars();msg(rotationLocked?'Giro con ratón bloqueado. Puedes desplazar, acercar y orientar con el cubo.':'Giro con ratón habilitado en Navegar.');}}]);
toolbar('Herramientas',[{text:'Abrir SKP',command:'open'},{text:'Navegar',mode:'navigate'},{text:'Mano',mode:'hand'},{text:'Seleccionar',mode:'select'},{text:'Medir',mode:'measure'},{text:'Cota',mode:'dimension'},{text:'Nivel',mode:'level'},{text:'Cero ±0',mode:'zero'}]);
toolbar('Selección',[{text:'Aislar',command:'isolate'},{text:'Ocultar',command:'hideSelected'},{text:'Mostrar todo',command:'restoreVisible'},{text:'Limpiar',command:'clearSelected'},{text:'Encuadrar',command:'fitSelected'}]);
toolbar('Exportar',[{text:'CAD',command:'dxf'},{text:'IFC',command:'ifc'},{text:'Revit JSON',command:'revit'},{text:'CSV',command:'csv'},{text:'Guardar sesión',command:'save'}]);
function syncToolbars(){if(!$('rotationLock'))return;$('rotationLock').textContent=rotationLocked?'Desbloquear giro':'Bloquear giro';$('rotationLock').setAttribute('aria-pressed',String(rotationLocked));$('rotationLock').classList.toggle('active',rotationLocked);for(const [id,value] of [['toolPerspective','perspective'],['toolOrtho','orthographic']]){$(id).classList.toggle('active',$('projection').value===value);$(id).setAttribute('aria-pressed',String($('projection').value===value));}}
syncToolbars();controls.enableRotate=!rotationLocked;new ResizeObserver(()=>{$('tip').style.top=(toolbars.offsetTop+toolbars.offsetHeight+8)+'px';}).observe(toolbars);
const projectionHandler=$('projection').onchange;$('projection').onchange=()=>{if((camera.isOrthographicCamera?'orthographic':'perspective')!==$('projection').value)projectionHandler();syncToolbars();};

new ResizeObserver(()=>{const w=view.clientWidth,h=view.clientHeight;renderer.setSize(w,h);resizeProjection();}).observe(view);
function animate(){requestAnimationFrame(animate);controls.update();updateCube();for(const {el,p} of labelAnchors){const screen=p.clone().project(camera);el.style.display=screen.z<-1||screen.z>1?'none':'block';el.style.left=((screen.x+1)*view.clientWidth/2)+'px';el.style.top=((1-screen.y)*view.clientHeight/2)+'px';}renderer.render(scene,camera);}animate();
fetch('./modelo.json').then(r=>{if(!r.ok)throw Error('No se encuentra modelo.json');return r.json();}).then(loadModel).catch(e=>msg('No se pudo cargar: '+e.message));
window.addEventListener('keydown',e=>{if(e.key==='Escape'){setMode('navigate');drawMarks();}});

function updatePanels(){for(const [id,css,label] of [['toggleTools','toolsHidden','barras'],['toggleSidebar','sidebarHidden','panel lateral']]){const hidden=document.body.classList.contains(css);$(id).textContent=(hidden?'Mostrar ':'Ocultar ')+label;$(id).setAttribute('aria-expanded',String(!hidden));}const full=!!document.fullscreenElement;$('fullscreen').textContent=full?'Salir de pantalla completa':'Pantalla completa';$('fullscreen').setAttribute('aria-pressed',String(full));}
for(const [id,css] of [['toggleTools','toolsHidden'],['toggleSidebar','sidebarHidden']]){try{document.body.classList.toggle(css,localStorage.getItem('odr-skp-'+css)==='true');}catch(e){}$(id).onclick=()=>{document.body.classList.toggle(css);try{localStorage.setItem('odr-skp-'+css,String(document.body.classList.contains(css)));}catch(e){}updatePanels();};}
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch(e){msg('Pantalla completa no disponible en este navegador. Puedes ocultar las barras y el panel lateral.');}};
document.addEventListener('fullscreenchange',updatePanels);updatePanels();

function updateEdges(){for(const mesh of modelGroup.children){let lines=mesh.children.find(o=>o.userData.edges);if(edgesVisible&&!lines){lines=new T.LineSegments(new T.EdgesGeometry(mesh.geometry,1),new T.LineBasicMaterial({color:0x20343f}));lines.userData.edges=true;mesh.add(lines);}if(lines){lines.visible=edgesVisible;filterEditedEdges(lines);}for(const child of mesh.children)if(child.userData.customEdges)child.visible=edgesVisible;}if($('toggleEdges')){$('toggleEdges').classList.toggle('active',edgesVisible);$('toggleEdges').setAttribute('aria-pressed',String(edgesVisible));}if($('edges'))$('edges').checked=edgesVisible;}
$('edges').checked=edgesVisible;$('edges').onchange=()=>{edgesVisible=$('edges').checked;try{localStorage.setItem('odr-skp-edges',edgesVisible);}catch(e){}updateEdges();};updateEdges();

const edgeSelection=new Map(),edgeHighlights=new T.Group();scene.add(edgeHighlights);
function clearEdgeSelection(){edgeSelection.clear();clear(edgeHighlights);}
function refreshEdgeSelection(){if($('propertyInfo'))showSelectionProperties();clear(edgeHighlights);const lines=[];let total=0;for(const {a,b} of edgeSelection.values()){lines.push(new T.Vector3(...a),new T.Vector3(...b));total+=Math.hypot(...a.map((v,i)=>v-b[i]));}if(lines.length)edgeHighlights.add(new T.LineSegments(new T.BufferGeometry().setFromPoints(lines),new T.LineBasicMaterial({color:0xff8a00,depthTest:false})));$('selectedItems').replaceChildren();for(const [key,{a,b}] of edgeSelection){const row=document.createElement('div');row.className='item';const remove=document.createElement('button');remove.textContent='×';remove.onclick=()=>{edgeSelection.delete(key);refreshEdgeSelection();};const text=document.createElement('small');text.textContent=(viewEdits.edges[edgeKey(a,b)]?.name||'Arista '+key)+' · '+fmt(Math.hypot(...a.map((v,i)=>v-b[i])))+' · A ('+a.map(fmt).join(', ')+') · B ('+b.map(fmt).join(', ')+')';row.append(remove,text);$('selectedItems').append(row);}$('selectionInfo').textContent=edgeSelection.size+' aristas seleccionadas · longitud total '+fmt(total);}
function edgeCandidates(){const out=[];modelGroup.children.forEach((mesh,i)=>{if(!mesh.visible)return;for(const line of mesh.children)if((line.userData.edges||line.userData.customEdges)&&line.visible)out.push({line,i});});return out;}
function applyEdges(items,e){if(!e.ctrlKey&&!e.shiftKey)edgeSelection.clear();for(const item of items){item.key=edgeKey(item.a,item.b);if(e.shiftKey)edgeSelection.delete(item.key);else edgeSelection.set(item.key,item);}refreshEdgeSelection();}
function pickEdge(e){const r=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,1-(e.clientY-r.top)/r.height*2),camera);ray.params.Line.threshold=camera.isOrthographicCamera?orthoHeight/camera.zoom/r.height*8:camera.position.distanceTo(controls.target)*2*Math.tan(camera.fov*Math.PI/360)/r.height*8;const candidates=edgeCandidates(),hits=ray.intersectObjects(candidates.map(c=>c.line),false);const hit=hits[0];if(!hit){applyEdges([],e);return;}const parent=candidates.find(c=>c.line===hit.object).i,p=hit.object.geometry.attributes.position,a=new T.Vector3().fromBufferAttribute(p,hit.index).toArray(),b=new T.Vector3().fromBufferAttribute(p,hit.index+1).toArray();applyEdges([{key:parent+':'+hit.index/2,a,b}],e);msg('Arista seleccionada · '+fmt(Math.hypot(...a.map((v,i)=>v-b[i]))));}
function rectangleEdges(start,e){const r=renderer.domElement.getBoundingClientRect(),xmin=(Math.min(start[0],e.clientX)-r.left)/r.width*2-1,xmax=(Math.max(start[0],e.clientX)-r.left)/r.width*2-1,ymin=1-(Math.max(start[1],e.clientY)-r.top)/r.height*2,ymax=1-(Math.min(start[1],e.clientY)-r.top)/r.height*2,cross=e.clientX<start[0],items=[];camera.updateMatrixWorld();const matrix=new T.Matrix4().multiplyMatrices(camera.projectionMatrix,camera.matrixWorldInverse),planes=[p=>p[3]+p[2],p=>p[3]-p[2],p=>p[0]-xmin*p[3],p=>xmax*p[3]-p[0],p=>p[1]-ymin*p[3],p=>ymax*p[3]-p[1]];for(const {line,i} of edgeCandidates()){const p=line.geometry.attributes.position;for(let j=0;j<p.count;j+=2){const a=new T.Vector3().fromBufferAttribute(p,j).toArray(),b=new T.Vector3().fromBufferAttribute(p,j+1).toArray(),vertices=[a,b].map(v=>new T.Vector4(...v,1).applyMatrix4(matrix).toArray());if(cross?clipPolygon(vertices,planes).length:vertices.every(v=>planes.every(plane=>plane(v)>=-1e-9)))items.push({key:i+':'+j/2,a,b});}}applyEdges(items,e);msg(items.length+' aristas encontradas por rectángulo.');}
$('selectionTarget').onchange=()=>{clearEdgeSelection();selected.clear();updateSelection();const type=$('selectionTarget').value;if(type==='pieces'){$('selectionDetail').value='groups';rebuildGeometry();}if(type==='faces'){$('selectionDetail').value='surfaces';rebuildGeometry();}if(type==='edges'){edgesVisible=true;updateEdges();refreshEdgeSelection();}setMode('select');};
const targetSelect=document.createElement('select');targetSelect.setAttribute('aria-label','Tipo de selección en barra');targetSelect.innerHTML=$('selectionTarget').innerHTML;toolbars.querySelector('[aria-label="Selección"]').prepend(targetSelect);targetSelect.onchange=()=>{$('selectionTarget').value=targetSelect.value;$('selectionTarget').onchange();};$('selectionTarget').addEventListener('change',()=>targetSelect.value=$('selectionTarget').value);

const meshKeys=new WeakMap();
function meshKey(m){if(meshKeys.has(m))return meshKeys.get(m);let h=2166136261;for(const v of m.positions){const t=v.toFixed(7);for(let j=0;j<t.length;j++){h^=t.charCodeAt(j);h=Math.imul(h,16777619);}h^=44;h=Math.imul(h,16777619);}const k=m.positions.length+':'+(h>>>0);meshKeys.set(m,k);return k;}
function edgeKey(a,b){return [a.map(v=>v.toFixed(7)).join(','),b.map(v=>v.toFixed(7)).join(',')].sort().join('|');}
function selectedEditItems(){return $('selectionTarget').value==='edges'?[...edgeSelection.values()].map(e=>({kind:'edges',key:edgeKey(e.a,e.b),a:e.a,b:e.b})):[...selected].map(i=>({kind:'meshes',key:meshKey(model.meshes[i]),i}));}
function applyViewEdits(){modelGroup.children.forEach((mesh,i)=>{const m=model.meshes[i];m.originalName??=m.name;const edit=viewEdits.meshes[meshKey(m)];const layer=viewEdits.layers.find(l=>l.id===edit?.layer);m.name=edit?.name||m.originalName;mesh.userData.baseColor??=mesh.material.color.getHex();mesh.material.color.set(layer?.color||edit?.color||mesh.userData.baseColor);const opacity=1-(edit?.transparency??layer?.transparency??0)/100;mesh.material.opacity=opacity;mesh.material.transparent=opacity<1;mesh.material.depthWrite=opacity===1;mesh.visible=layer?.visible!==false;for(const child of [...mesh.children])if(child.userData.customEdges){child.geometry.dispose();child.material.dispose();mesh.remove(child);}const positions=new Map();for(const edit of Object.values(viewEdits.edges)){const edgeLayer=viewEdits.layers.find(l=>l.id===edit.layer);if(!Array.isArray(edit.a)||!Array.isArray(edit.b)||edgeLayer?.visible===false)continue;if(hasGeometryPoint(m.positions,edit.a)&&hasGeometryPoint(m.positions,edit.b)){const line=new T.LineSegments(new T.BufferGeometry().setFromPoints([new T.Vector3(...edit.a),new T.Vector3(...edit.b)]),new T.LineBasicMaterial({color:edgeLayer?.color||edit.color||0x20343f,transparent:true,opacity:1-(edit.transparency??edgeLayer?.transparency??0)/100}));line.userData.customEdges=true;line.visible=edgesVisible;mesh.add(line);}}});modelGroup.children.forEach(mesh=>{const base=mesh.children.find(o=>o.userData.edges);if(base)filterEditedEdges(base);});Array.from($('groups').querySelectorAll('span')).forEach((span,i)=>{span.textContent=model.meshes[i].name;span.title=span.textContent;});}
function editSelected(field){const items=selectedEditItems();if(!items.length)return msg('Selecciona primero caras, piezas o aristas.');const value=field==='name'?$('editName').value.trim():$('editColor').value;if(!value)return msg('Escribe un nombre.');items.forEach((item,i)=>{const edit=viewEdits[item.kind][item.key]||{};if(item.kind==='edges'){edit.a=item.a;edit.b=item.b;}edit[field]=field==='name'&&items.length>1?value+' '+(i+1):value;viewEdits[item.kind][item.key]=edit;});applyViewEdits();if($('selectionTarget').value==='edges')refreshEdgeSelection();else updateSelection();msg('Aplicado '+(field==='name'?'nombre':'color')+' a '+items.length+' elementos. Guarda la sesión para conservarlo.');}
$('nameSelection').onclick=()=>editSelected('name');$('colorSelection').onclick=()=>editSelected('color');$('resetSelectionStyle').onclick=()=>{for(const item of selectedEditItems())delete viewEdits[item.kind][item.key];applyViewEdits();if($('selectionTarget').value==='edges')refreshEdgeSelection();else updateSelection();};
$('createUserGroup').onclick=()=>{const items=selectedEditItems();if(!items.length)return msg('Selecciona los elementos del grupo.');const name=$('editName').value.trim()||'Grupo '+(viewEdits.groups.length+1);viewEdits.groups.push({name,type:$('selectionTarget').value,detail:$('selectionDetail').value,items});renderUserGroups();msg('Grupo '+name+' creado con '+items.length+' elementos.');};
function renderUserGroups(){if(!$('userGroups'))return;$('userGroups').replaceChildren();viewEdits.groups.forEach((group,i)=>{const row=document.createElement('div');row.className='item';const title=document.createElement('span');title.textContent=group.name+' · '+group.items.length+' elementos';const select=document.createElement('button');select.textContent='Seleccionar';select.onclick=()=>{if($('selectionDetail').value!==group.detail){$('selectionDetail').value=group.detail;rebuildGeometry();}$('selectionTarget').value=group.type;targetSelect.value=group.type;selected.clear();clearEdgeSelection();if(group.type==='edges'){edgesVisible=true;updateEdges();for(const item of group.items)edgeSelection.set(item.key,item);refreshEdgeSelection();}else{const keys=new Set(group.items.map(item=>item.key));model.meshes.forEach((m,index)=>{if(keys.has(meshKey(m))){selected.add(index);modelGroup.children[index].visible=true;}});syncVisibility();updateSelection();}setMode('select');msg('Grupo '+group.name+' seleccionado.');};const remove=document.createElement('button');remove.textContent='×';remove.title='Eliminar grupo';remove.onclick=()=>{viewEdits.groups.splice(i,1);renderUserGroups();};row.append(remove,select,title);$('userGroups').append(row);});}
function restoreViewEdits(d){if(!d)return;const safeColor=c=>typeof c==='string'&&/^#[0-9a-f]{6}$/i.test(c),point=p=>Array.isArray(p)&&p.length===3&&p.every(Number.isFinite);viewEdits={meshes:{},edges:{},groups:[],layers:[]};for(const kind of ['meshes','edges'])for(const [key,value] of Object.entries(d[kind]||{})){if(!value||typeof value!=='object')continue;const edit={};if(typeof value.name==='string')edit.name=value.name;if(safeColor(value.color))edit.color=value.color;if(typeof value.layer==='string')edit.layer=value.layer;if(Number.isFinite(value.transparency))edit.transparency=Math.max(0,Math.min(100,value.transparency));if(value.parameters&&typeof value.parameters==='object')edit.parameters=Object.fromEntries(Object.entries(value.parameters).filter(([k,v])=>typeof v==='string'));if(kind==='edges'){if(!point(value.a)||!point(value.b))continue;edit.a=value.a;edit.b=value.b;}viewEdits[kind][key]=edit;}if(Array.isArray(d.groups))viewEdits.groups=d.groups.filter(g=>g&&typeof g.name==='string'&&['pieces','faces','edges'].includes(g.type)&&['groups','surfaces','connected'].includes(g.detail)&&Array.isArray(g.items)&&g.items.every(item=>item&&typeof item.key==='string'&&(g.type!=='edges'||point(item.a)&&point(item.b))));if(Array.isArray(d.layers))viewEdits.layers=d.layers.filter(l=>l&&typeof l.id==='string'&&typeof l.name==='string'&&safeColor(l.color)).map(l=>({...l,transparency:Number.isFinite(l.transparency)?Math.max(0,Math.min(100,l.transparency)):0,visible:l.visible!==false}));applyViewEdits();renderUserGroups();renderLayers();}
toolbar('Editar',[{text:'Nombre / color',action:()=>{document.body.classList.remove('sidebarHidden');updatePanels();$('editName').scrollIntoView({block:'center'});$('editName').focus();}},{text:'Crear grupo',command:'createUserGroup'}]);renderUserGroups();

const propertyIsolation=new T.Group();scene.add(propertyIsolation);
function layerFor(edit){return viewEdits.layers.find(l=>l.id===edit?.layer);}
function selectedProperties(){return selectedEditItems().map(item=>{const edit=viewEdits[item.kind][item.key]||{},layer=layerFor(edit);return {nombre:edit.name|| (item.kind==='meshes'?model.meshes[item.i].name:'Arista'),capa:layer?.name||'Sin capa',transparencia:layer?.transparency??edit.transparency??0,parametros:{...layer?.parameters,...edit.parameters}};});}
function showSelectionProperties(){if(!$('propertyInfo'))return;$('propertyInfo').textContent=JSON.stringify(selectedProperties().slice(0,8),null,2);}
function modifySelected(fn){const items=selectedEditItems();if(!items.length)return msg('Selecciona elementos primero.');for(const item of items){const edit=viewEdits[item.kind][item.key]||{};if(item.kind==='edges'){edit.a=item.a;edit.b=item.b;}fn(edit,item);viewEdits[item.kind][item.key]=edit;}clear(propertyIsolation);applyViewEdits();syncVisibility();if($('selectionTarget').value==='edges')refreshEdgeSelection();else updateSelection();msg('Propiedades aplicadas a '+items.length+' elementos.');}
$('setTransparency').onclick=()=>{const t=Number($('editTransparency').value);if(!Number.isFinite(t)||t<0||t>100)return msg('Transparencia entre 0 y 100.');modifySelected(edit=>{edit.transparency=t;});};
$('assignLayer').onclick=()=>modifySelected(edit=>{if($('activeLayer').value)edit.layer=$('activeLayer').value;else delete edit.layer;});
$('newLayer').onclick=()=>{const name=$('layerName').value.trim();if(!name)return msg('Escribe un nombre de capa.');if(viewEdits.layers.some(l=>l.name.toLowerCase()===name.toLowerCase()))return msg('Ya existe una capa con ese nombre.');const id=crypto.randomUUID();viewEdits.layers.push({id,name,color:$('editColor').value,transparency:0,visible:true,parameters:{}});renderLayers();$('activeLayer').value=id;msg('Capa creada. Selecciona elementos y pulsa Asignar selección a capa.');};
function parameterInput(){const name=$('paramName').value.trim(),value=$('paramValue').value;return name?{name,value}:null;}
$('setParameter').onclick=()=>{const p=parameterInput();if(!p)return msg('Escribe el nombre del parámetro.');if(p.name.toLowerCase()==='nombre'){$('editName').value=p.value;editSelected('name');}else modifySelected(edit=>{edit.parameters={...edit.parameters,[p.name]:p.value};});showSelectionProperties();};
$('layerParameter').onclick=()=>{const layer=viewEdits.layers.find(l=>l.id===$('activeLayer').value),p=parameterInput();if(!layer||!p)return msg('Elige una capa y escribe un parámetro.');if(p.name.toLowerCase()==='nombre')layer.name=p.value;else layer.parameters={...layer.parameters,[p.name]:p.value};renderLayers();showSelectionProperties();};
function renderLayers(){if(!$('layerList'))return;const active=$('activeLayer').value;$('activeLayer').replaceChildren(new Option('Sin capa',''));$('layerList').replaceChildren();for(const layer of viewEdits.layers){$('activeLayer').append(new Option(layer.name,layer.id));const row=document.createElement('div');row.className='item';const name=document.createElement('input');name.value=layer.name;name.setAttribute('aria-label','Nombre de capa '+layer.name);name.onchange=()=>{layer.name=name.value.trim()||layer.name;renderLayers();};const color=document.createElement('input');color.type='color';color.value=layer.color;color.style.width='48px';color.setAttribute('aria-label','Color capa '+layer.name);const opacity=document.createElement('input');opacity.type='number';opacity.min=0;opacity.max=100;opacity.value=layer.transparency;opacity.style.width='65px';opacity.setAttribute('aria-label','Transparencia capa '+layer.name);const visible=document.createElement('input');visible.type='checkbox';visible.checked=layer.visible;visible.setAttribute('aria-label','Visible capa '+layer.name);const apply=()=>{clear(propertyIsolation);applyViewEdits();syncVisibility();showSelectionProperties();};color.onchange=()=>{layer.color=color.value;apply();};opacity.onchange=()=>{layer.transparency=Math.max(0,Math.min(100,Number(opacity.value)||0));apply();};visible.onchange=()=>{layer.visible=visible.checked;apply();};const isolate=document.createElement('button');isolate.textContent='Aislar';isolate.onclick=()=>isolateProperties((edit,m)=>edit?.layer===layer.id);const info=document.createElement('small');info.textContent='Visible · color · transparencia %';row.append(name,visible,color,opacity,isolate,info);$('layerList').append(row);}$('activeLayer').value=active;}
function isolateProperties(test){clear(propertyIsolation);let count=0;modelGroup.children.forEach((mesh,i)=>{const edit=viewEdits.meshes[meshKey(model.meshes[i])];mesh.visible=test(edit,model.meshes[i],mesh.material.color.getHexString());if(mesh.visible)count++;});for(const edit of Object.values(viewEdits.edges)){const layer=layerFor(edit),color=(layer?.color||edit.color||'#20343f').slice(1);if(!test(edit,{name:edit.name||''},color)||!edit.a||!edit.b)continue;propertyIsolation.add(new T.LineSegments(new T.BufferGeometry().setFromPoints([new T.Vector3(...edit.a),new T.Vector3(...edit.b)]),new T.LineBasicMaterial({color:'#'+color,transparent:true,opacity:1-(layer?.transparency??edit.transparency??0)/100})));count++;}syncVisibility();msg(count+' elementos aislados. Mostrar todo recupera el modelo.');}
$('isolateName').onclick=()=>{const name=$('filterName').value.trim().toLowerCase();if(!name)return msg('Escribe el nombre a buscar.');isolateProperties((edit,m)=>String(edit?.name||m.name).toLowerCase().includes(name));};
$('isolateColor').onclick=()=>{const color=$('editColor').value.slice(1).toLowerCase();isolateProperties((edit,m,current)=>current.toLowerCase()===color);};
const restoreAllHandler=$('restoreVisible').onclick;$('restoreVisible').onclick=()=>{clear(propertyIsolation);restoreAllHandler();applyViewEdits();syncVisibility();};
toolbar('Capas',[{text:'Capas / propiedades',action:()=>{document.body.classList.remove('sidebarHidden');updatePanels();$('layerName').scrollIntoView({block:'center'});$('layerName').focus();}},{text:'Aislar nombre',command:'isolateName'},{text:'Aislar color',command:'isolateColor'}]);renderLayers();

function filterEditedEdges(line){line.userData.fullEdges??=Array.from(line.geometry.attributes.position.array);const all=line.userData.fullEdges,out=[];for(let j=0;j<all.length;j+=6){const a=all.slice(j,j+3),b=all.slice(j+3,j+6);if(!viewEdits.edges[edgeKey(a,b)])for(let k=j;k<j+6;k++)out.push(all[k]);}line.geometry.setAttribute('position',new T.Float32BufferAttribute(out,3));line.geometry.computeBoundingSphere();}

function hasGeometryPoint(p,v){for(let i=0;i<p.length;i+=3)if(Math.hypot(p[i]-v[0],p[i+1]-v[1],p[i+2]-v[2])<.0001)return true;return false;}

function cadExportEdges(){if(!$('geometry').checked)return [];const candidates=$('exportSelected').checked&&$('selectionTarget').value==='edges'?[...edgeSelection.values()]:Object.values(viewEdits.edges);return candidates.filter(e=>layerFor(viewEdits.edges[edgeKey(e.a,e.b)]||e)?.visible!==false).map(e=>{const edit=viewEdits.edges[edgeKey(e.a,e.b)]||e,layer=layerFor(edit);return {...e,name:edit.name||'Arista',cadLayer:layer?.name||'SKP_ARISTAS',color:layer?.color||edit.color,transparency:edit.transparency??layer?.transparency??0,parameters:{...layer?.parameters,...edit.parameters}};});}
