import assert from 'node:assert/strict';
import fs from 'node:fs';
import {sessionData,dxf,ifc,csv} from './exporters.js';
import {components,axisValue,projectedEnd,detectElevations,indexedMesh} from './measurement.js';
const a=[1,2,3],b=[4,6,15];
assert.equal(axisValue(a,b,'x'),3);assert.equal(axisValue(a,b,'y'),4);assert.equal(axisValue(a,b,'z'),12);assert.equal(axisValue(a,b,'xy'),5);assert.equal(axisValue(a,b,'3d'),13);
assert.deepEqual(projectedEnd(a,b,'z'),[1,2,15]);assert.equal(components(b,a).dz,-12);
const planes=[{positions:[0,0,2,2,0,2,0,2,2, 0,0,5,2,0,5,0,2,5]}];
assert.deepEqual(detectElevations(planes,.01,1).map(p=>p.z),[2,5]);
assert.equal(indexedMesh(planes[0].positions).closed,false);
const compact=indexedMesh([0,0,0,1,0,0,0,1,0, 0,0,0,0,1,0,0,0,1]);assert.equal(compact.vertices.length,4);
const model=JSON.parse(fs.readFileSync(new URL('./modelo.json',import.meta.url),'utf8'));
const levels=[{name:'Prueba ±0',p:[1,2,4]},{name:'Prueba +3',p:[1,2,7]}];
const measurements=[{name:'Triangulo 3-4-5',a:[0,0,4],b:[3,0,8]}];
const data=sessionData(model,4,levels,measurements);
assert.equal(data.levels[1].elevation,3);assert.deepEqual(data.measurements[0].b,[3,0,4]);
assert.equal(Math.hypot(...data.measurements[0].b),5);
assert.ok(csv(data).includes('"5";"3";"4"'));
const cad=dxf(data);assert.ok(cad.includes('$INSUNITS\r\n70\r\n5'));
const bim=ifc(data,model.meshes);assert.equal((bim.match(/IFCBUILDINGSTOREY\(/g)||[]).length,2);
const dedup=ifc({...data,levels:[...data.levels,{...data.levels[0],name:'Cota duplicada'},{name:'Solo punto',point:[0,0,9],elevation:9,storey:false}]});assert.equal((dedup.match(/IFCBUILDINGSTOREY\(/g)||[]).length,2);
assert.ok(bim.includes('ODR_Levantamiento_SKP'));
assert.equal((bim.match(/IFCTRIANGULATEDFACESET\(/g)||[]).length,model.meshes.length);
const root=new URL('./pruebas/',import.meta.url);fs.mkdirSync(root,{recursive:true});
fs.writeFileSync(new URL('PRUEBA_NO_USAR_EN_PROYECTO.ifc',root),bim);
fs.writeFileSync(new URL('PRUEBA_NO_USAR_EN_PROYECTO.dxf',root),dxf(data,model.meshes));
fs.writeFileSync(new URL('PRUEBA_NO_USAR_EN_PROYECTO.json',root),JSON.stringify(data,null,2));
console.log('OK: metros/centimetros, cero relativo, distancia 3-4-5, IFC con 2 plantas y '+model.meshes.length+' mallas. Datos de prueba, no niveles del edificio.');
